-- Book Manager — Schema

-- Usuários
CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150) NOT NULL,
    email          VARCHAR(180) NOT NULL,
    senha          VARCHAR(255) NOT NULL,
    perfil         VARCHAR(20)  NOT NULL,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_usuario_email_ativo ON usuario (LOWER(email)) WHERE removido = FALSE;

-- Livros
CREATE TABLE livro (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(250) NOT NULL,
    autor          VARCHAR(200) NOT NULL,
    ano            INTEGER,
    descricao      TEXT,
    url_capa       VARCHAR(500),
    isbn           VARCHAR(20),
    total_paginas  INTEGER,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_livro_titulo ON livro (LOWER(titulo));
