-- Book Manager — Schema

-- Usuários
CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150) NOT NULL,
    email          VARCHAR(180) NOT NULL,
    senha          VARCHAR(255) NOT NULL,
    perfil           VARCHAR(20)  NOT NULL,
    email_confirmado BOOLEAN      NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_usuario_email_ativo ON usuario (LOWER(email)) WHERE removido = FALSE;

-- Tokens de Confirmação de Email e Redefinição de Senha
CREATE TABLE token_verificacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT       NOT NULL REFERENCES usuario (id),
    token_hash     VARCHAR(64)  NOT NULL,
    tipo           VARCHAR(30)  NOT NULL,
    expira_em      TIMESTAMPTZ  NOT NULL,
    usado_em       TIMESTAMPTZ,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_token_verificacao_hash ON token_verificacao (token_hash);
CREATE INDEX ix_token_verificacao_usuario ON token_verificacao (usuario_id, tipo);

-- Livros
CREATE TABLE livro (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(250) NOT NULL,
    autor          VARCHAR(200) NOT NULL,
    ano            INTEGER,
    descricao      TEXT,
    url_capa       VARCHAR(500),
    isbn           VARCHAR(20),
    total_paginas  INTEGER,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_livro_titulo ON livro (LOWER(titulo));
