-- Book Manager — Schema

-- Usuários
CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150) NOT NULL,
    email          VARCHAR(180) NOT NULL,
    senha          VARCHAR(255) NOT NULL,
    perfil           VARCHAR(20)  NOT NULL,
    email_confirmado BOOLEAN      NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_usuario_email_ativo ON usuario (LOWER(email)) WHERE removido = FALSE;

-- Tokens de Confirmação de Email e Redefinição de Senha
CREATE TABLE token_verificacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT       NOT NULL REFERENCES usuario (id),
    token_hash     VARCHAR(64)  NOT NULL,
    tipo           VARCHAR(30)  NOT NULL,
    expira_em      TIMESTAMPTZ  NOT NULL,
    usado_em       TIMESTAMPTZ,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_token_verificacao_hash ON token_verificacao (token_hash);
CREATE INDEX ix_token_verificacao_usuario ON token_verificacao (usuario_id, tipo);

-- Livros
CREATE TABLE livro (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR(250) NOT NULL,
    autor            VARCHAR(200) NOT NULL,
    ano              INTEGER,
    descricao        TEXT,
    url_capa         VARCHAR(500),
    isbn             VARCHAR(20),
    total_paginas    INTEGER,
    google_id        VARCHAR(64),
    subtitulo        VARCHAR(300),
    editora          VARCHAR(200),
    data_publicacao  VARCHAR(20),
    idioma           VARCHAR(10),
    media_avaliacao  NUMERIC(2,1),
    total_avaliacoes INTEGER,
    link_previa      VARCHAR(500),
    criado_em        TIMESTAMPTZ  NOT NULL,
    atualizado_em    TIMESTAMPTZ  NOT NULL,
    criado_por       VARCHAR(150),
    atualizado_por   VARCHAR(150),
    removido         BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_livro_titulo ON livro (LOWER(titulo));
CREATE UNIQUE INDEX ux_livro_google_id ON livro (google_id) WHERE removido = FALSE;
CREATE INDEX ix_livro_media_avaliacao ON livro (media_avaliacao DESC NULLS LAST);

-- Categorias
CREATE TABLE categoria (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(120) NOT NULL,
    slug           VARCHAR(120) NOT NULL,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_categoria_slug ON categoria (slug) WHERE removido = FALSE;

CREATE TABLE livro_categoria (
    livro_id     BIGINT NOT NULL REFERENCES livro (id),
    categoria_id BIGINT NOT NULL REFERENCES categoria (id),
    PRIMARY KEY (livro_id, categoria_id)
);

CREATE INDEX ix_livro_categoria_categoria ON livro_categoria (categoria_id);

-- Avaliações com Resenha Opcional (Uma Por User <-> Livro)
CREATE TABLE avaliacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL REFERENCES usuario (id),
    livro_id       BIGINT      NOT NULL REFERENCES livro (id),
    nota           SMALLINT    NOT NULL CHECK (nota BETWEEN 1 AND 5),
    resenha        TEXT,
    spoiler        BOOLEAN     NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMPTZ NOT NULL,
    atualizado_em  TIMESTAMPTZ NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_avaliacao_usuario_livro
    ON avaliacao (usuario_id, livro_id) WHERE removido = FALSE;
CREATE INDEX ix_avaliacao_livro ON avaliacao (livro_id);

-- Comentários
CREATE TABLE comentario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL REFERENCES usuario (id),
    livro_id       BIGINT      NOT NULL REFERENCES livro (id),
    texto          TEXT        NOT NULL,
    spoiler        BOOLEAN     NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMPTZ NOT NULL,
    atualizado_em  TIMESTAMPTZ NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_comentario_livro ON comentario (livro_id, criado_em DESC);

-- Estante do Leitor: Status de Leitura, Favorito e Progresso
CREATE TABLE estante (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL REFERENCES usuario (id),
    livro_id       BIGINT      NOT NULL REFERENCES livro (id),
    status         VARCHAR(20) NOT NULL,
    favorito       BOOLEAN     NOT NULL DEFAULT FALSE,
    pagina_atual   INTEGER,
    total_paginas  INTEGER,
    criado_em      TIMESTAMPTZ NOT NULL,
    atualizado_em  TIMESTAMPTZ NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_estante_usuario_livro
    ON estante (usuario_id, livro_id) WHERE removido = FALSE;
CREATE INDEX ix_estante_usuario_status ON estante (usuario_id, status);
CREATE INDEX ix_estante_livro ON estante (livro_id);
