-- V2: Confirmacao de e-mail e redefinicao de senha

ALTER TABLE usuario ADD COLUMN email_confirmado BOOLEAN NOT NULL DEFAULT FALSE;

-- Contas Criadas Antes da Migration Ficam com o E-mail Confirmado
UPDATE usuario SET email_confirmado = TRUE;

CREATE TABLE token_verificacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT       NOT NULL REFERENCES usuario (id),
    token_hash     VARCHAR(64)  NOT NULL,
    tipo           VARCHAR(30)  NOT NULL,
    expira_em      TIMESTAMPTZ  NOT NULL,
    usado_em       TIMESTAMPTZ,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_token_verificacao_hash ON token_verificacao (token_hash);
CREATE INDEX ix_token_verificacao_usuario ON token_verificacao (usuario_id, tipo);
