-- V3: Campos do Google Books e categorias

ALTER TABLE livro
    ADD COLUMN google_id        VARCHAR(64),
    ADD COLUMN subtitulo        VARCHAR(300),
    ADD COLUMN editora          VARCHAR(200),
    ADD COLUMN data_publicacao  VARCHAR(20),
    ADD COLUMN idioma           VARCHAR(10),
    ADD COLUMN media_avaliacao  NUMERIC(2,1),
    ADD COLUMN total_avaliacoes INTEGER,
    ADD COLUMN link_previa      VARCHAR(500);

-- Deduplicacao da Importacao (Apenas Entre Livros Ativos)
CREATE UNIQUE INDEX ux_livro_google_id ON livro (google_id) WHERE removido = FALSE;

CREATE TABLE categoria (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(120) NOT NULL,
    slug           VARCHAR(120) NOT NULL,
    criado_em      TIMESTAMPTZ  NOT NULL,
    atualizado_em  TIMESTAMPTZ  NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_categoria_slug ON categoria (slug) WHERE removido = FALSE;

-- Juncao Pura: sem Auditoria e sem Soft Delete
CREATE TABLE livro_categoria (
    livro_id     BIGINT NOT NULL REFERENCES livro (id),
    categoria_id BIGINT NOT NULL REFERENCES categoria (id),
    PRIMARY KEY (livro_id, categoria_id)
);

CREATE INDEX ix_livro_categoria_categoria ON livro_categoria (categoria_id);
CREATE INDEX ix_livro_media_avaliacao ON livro (media_avaliacao DESC NULLS LAST);
