-- V4: Avaliacoes (nota + resenha) e comentarios por livro

CREATE TABLE avaliacao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL REFERENCES usuario (id),
    livro_id       BIGINT      NOT NULL REFERENCES livro (id),
    nota           SMALLINT    NOT NULL CHECK (nota BETWEEN 1 AND 5),
    resenha        TEXT,
    spoiler        BOOLEAN     NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMPTZ NOT NULL,
    atualizado_em  TIMESTAMPTZ NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN     NOT NULL DEFAULT FALSE
);

-- Uma Avaliacao por Usuario em Cada Livro (Entre as Ativas)
CREATE UNIQUE INDEX ux_avaliacao_usuario_livro
    ON avaliacao (usuario_id, livro_id) WHERE removido = FALSE;
CREATE INDEX ix_avaliacao_livro ON avaliacao (livro_id);

-- Conversa Livre: Varios Comentarios por Usuario em Cada Livro
CREATE TABLE comentario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL REFERENCES usuario (id),
    livro_id       BIGINT      NOT NULL REFERENCES livro (id),
    texto          TEXT        NOT NULL,
    spoiler        BOOLEAN     NOT NULL DEFAULT FALSE,
    criado_em      TIMESTAMPTZ NOT NULL,
    atualizado_em  TIMESTAMPTZ NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_comentario_livro ON comentario (livro_id, criado_em DESC);
