-- V5: Estante do leitor (status, favorito e progresso)

CREATE TABLE estante (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL REFERENCES usuario (id),
    livro_id       BIGINT      NOT NULL REFERENCES livro (id),
    status         VARCHAR(20) NOT NULL,
    favorito       BOOLEAN     NOT NULL DEFAULT FALSE,
    pagina_atual   INTEGER,
    -- Preenchido a Mao Quando o Livro Nao Traz pageCount do Google
    total_paginas  INTEGER,
    criado_em      TIMESTAMPTZ NOT NULL,
    atualizado_em  TIMESTAMPTZ NOT NULL,
    criado_por     VARCHAR(150),
    atualizado_por VARCHAR(150),
    removido       BOOLEAN     NOT NULL DEFAULT FALSE
);

-- Um Livro Ocupa Uma Vaga So na Estante de Cada Leitor
CREATE UNIQUE INDEX ux_estante_usuario_livro
    ON estante (usuario_id, livro_id) WHERE removido = FALSE;
CREATE INDEX ix_estante_usuario_status ON estante (usuario_id, status);
CREATE INDEX ix_estante_livro ON estante (livro_id);
