package com.bookmanager.categoria;

import java.util.Map;

// Traduz os Rotulos que o Google Books Devolve em Ingles
final class NomesDeCategoria {

    private static final Map<String, String> TRADUCAO = Map.ofEntries(
            Map.entry("education", "Educação"),
            Map.entry("fiction", "Ficção"),
            Map.entry("business-economics", "Negócios e Economia"),
            Map.entry("history", "História"),
            Map.entry("law", "Direito"),
            Map.entry("computers", "Computação"),
            Map.entry("cooking", "Culinária"),
            Map.entry("brazil", "Brasil"),
            Map.entry("philosophy", "Filosofia"),
            Map.entry("music", "Música"),
            Map.entry("self-help", "Autoajuda"),
            Map.entry("poetry", "Poesia"),
            Map.entry("psychology", "Psicologia"),
            Map.entry("medicine", "Medicina"),
            Map.entry("medical", "Saúde e Medicina"),
            Map.entry("literary-criticism", "Crítica Literária"),
            Map.entry("technology-engineering", "Tecnologia e Engenharia"),
            Map.entry("brazilian-literature", "Literatura Brasileira"),
            Map.entry("brazilian-fiction", "Ficção Brasileira"),
            Map.entry("latin-america", "América Latina"),
            Map.entry("juvenile-fiction", "Ficção Infantojuvenil"),
            Map.entry("juvenile-nonfiction", "Infantojuvenil"),
            Map.entry("social-science", "Ciências Sociais"),
            Map.entry("political-science", "Ciência Política"),
            Map.entry("language-arts-disciplines", "Letras e Linguagem"),
            Map.entry("literary-collections", "Coletâneas Literárias"),
            Map.entry("science", "Ciência"),
            Map.entry("religion", "Religião"),
            Map.entry("biography-autobiography", "Biografia"),
            Map.entry("library-catalogs", "Catálogos de Biblioteca"),
            Map.entry("antiques-collectibles", "Antiguidades e Coleções"),
            Map.entry("electronic-journals", "Periódicos Eletrônicos"),
            Map.entry("reference", "Referência"),
            Map.entry("agriculture", "Agricultura"),
            Map.entry("portugal", "Portugal"),
            Map.entry("american-literature", "Literatura Americana"),
            Map.entry("italian-literature", "Literatura Italiana"),
            Map.entry("english-literature", "Literatura Inglesa"),
            Map.entry("portuguese-literature", "Literatura Portuguesa"),
            Map.entry("universities-and-colleges", "Universidades"),
            Map.entry("accounting", "Contabilidade"),
            Map.entry("italian-language", "Língua Italiana"),
            Map.entry("mathematics", "Matemática"),
            Map.entry("art", "Arte"),
            Map.entry("architecture", "Arquitetura"),
            Map.entry("drama", "Teatro"),
            Map.entry("performing-arts", "Artes Cênicas"),
            Map.entry("comics-graphic-novels", "Quadrinhos"),
            Map.entry("true-crime", "Crimes Reais"),
            Map.entry("travel", "Viagem"),
            Map.entry("sports-recreation", "Esportes e Lazer"),
            Map.entry("health-fitness", "Saúde e Bem-Estar"),
            Map.entry("family-relationships", "Família e Relacionamentos"),
            Map.entry("nature", "Natureza"),
            Map.entry("photography", "Fotografia"),
            Map.entry("humor", "Humor"),
            Map.entry("gardening", "Jardinagem"),
            Map.entry("crafts-hobbies", "Artesanato e Hobbies"),
            Map.entry("games-activities", "Jogos e Atividades"),
            Map.entry("study-aids", "Material de Estudo"),
            Map.entry("foreign-language-study", "Estudo de Idiomas"),
            Map.entry("transportation", "Transportes"),
            Map.entry("body-mind-spirit", "Corpo, Mente e Espírito"),
            Map.entry("design", "Design"),
            Map.entry("house-home", "Casa e Decoração"),
            Map.entry("pets", "Animais de Estimação"),
            Map.entry("bibles", "Bíblias"),
            Map.entry("literature", "Literatura"),
            Map.entry("authors-brazilian", "Autores Brasileiros"),
            Map.entry("economics", "Economia"),
            Map.entry("engineering", "Engenharia"),
            Map.entry("nursing", "Enfermagem"),
            Map.entry("dentistry", "Odontologia"),
            Map.entry("veterinary-medicine", "Medicina Veterinária"),
            Map.entry("sociology", "Sociologia"),
            Map.entry("anthropology", "Antropologia"),
            Map.entry("geography", "Geografia"),
            Map.entry("linguistics", "Linguística"),
            Map.entry("archaeology", "Arqueologia"),
            Map.entry("theology", "Teologia"),
            Map.entry("ecology", "Ecologia"),
            Map.entry("physics", "Física"),
            Map.entry("chemistry", "Química"),
            Map.entry("biology", "Biologia"),
            Map.entry("astronomy", "Astronomia"),
            Map.entry("statistics", "Estatística"),
            Map.entry("management", "Administração"),
            Map.entry("marketing", "Marketing"),
            Map.entry("finance", "Finanças"),
            Map.entry("advertising", "Publicidade"),
            Map.entry("journalism", "Jornalismo"),
            Map.entry("cinema", "Cinema"),
            Map.entry("theater", "Teatro"),
            Map.entry("dance", "Dança"),
            Map.entry("fantasy", "Fantasia"),
            Map.entry("science-fiction", "Ficção Científica"),
            Map.entry("detective-and-mystery-stories", "Mistério e Suspense"),
            Map.entry("horror-tales", "Terror"),
            Map.entry("love-stories", "Romance"),
            Map.entry("short-stories", "Contos"),
            Map.entry("essays", "Ensaios"),
            Map.entry("children-s-stories", "Histórias Infantis"));

    private NomesDeCategoria() {
    }

    // Slug e a Chave Estavel; o Rotulo Original Vale como Reserva
    static String traduzir(String slug, String nomeOriginal) {
        return TRADUCAO.getOrDefault(slug, nomeOriginal);
    }
}
